# Generated by Django 5.0.3 on 2024-03-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_phto_car_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='phto',
            new_name='photo',
        ),
    ]
