# Generated by Django 5.0.3 on 2024-04-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinventory',
            old_name='cars_values',
            new_name='cars_value',
        ),
    ]
